### ISSUE TITLE
Cannot build yder - Arch Linux

### ISSUE THREAD

**Issue by emmaisadev** [dxing97/libdiscord#3]
As there is no package for ulfius on Arch, one must compile it from source. The first step here would be to compile orcania, which completes successfully as follows:

`daniel@XPS15 ~/ulfius/lib/orcania (git)-[heads/master] % make && sudo make install
cd ./src && make
make[1]: Entering directory '/home/daniel/ulfius/lib/orcania/src'
gcc -c -fPIC -Wall -D_REENTRANT -O3  memory.c
gcc -c -fPIC -Wall -D_REENTRANT -O3  orcania.c
gcc -c -fPIC -Wall -D_REENTRANT -O3  base64.c
gcc -shared -Wl,-soname,liborcania.so -o liborcania.so.1.1.1 orcania.o memory.o base64.o -lc -ljansson
ln -sf liborcania.so.1.1.1 liborcania.so
make[1]: Leaving directory '/home/daniel/ulfius/lib/orcania/src'
cd ./src && make install
make[1]: Entering directory '/home/daniel/ulfius/lib/orcania/src'
cp liborcania.so.1.1.1 /usr/local/lib
cp orcania.h /usr/local/include
ldconfig
make[1]: Leaving directory '/home/daniel/ulfius/lib/orcania/src'`

This then leads to compiling and installing yder, which uses orcania as a dependency. This fails, despite orcania installing successfully.

`daniel@XPS15 ~/ulfius/lib/yder (git)-[1252caa...] % make && sudo make install
cd ./src && make
make[1]: Entering directory '/home/daniel/ulfius/lib/yder/src'
gcc -c -fPIC -Wall -D_REENTRANT -O3 yder.c
gcc -shared -Wl,-soname,libyder.so -o libyder.so.2.0 yder.o -lc -lorcania
/usr/bin/ld: cannot find -lorcania
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:31: libyder.so] Error 1
make[1]: Leaving directory '/home/daniel/ulfius/lib/yder/src'
make: *** [Makefile:38: libyder.so] Error 2`

**Comment by dxing97** [comment]
[Looks like Ulfius was added to the AUR for Arch a couple of days ago.](https://github.com/babelouest/ulfius/issues/51)
